language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t alenaliapko/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alenaliapko/docker-react npm run test